version: '3'

services:
  publicsubmission:
    image: nlpcore/publicsubmission
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: PublicSubmission/Dockerfile
      
    depends_on:
      - spacy-rest

  spacy-rest:
    image: nlpcore/spacy-rest
    ports:
      - 8000:8000
    build: 
      context: SpacyServer
    volumes:
      - .:/SpacyServer
